[package]
name = "poc-cdp-raw"
edition.workspace = true
publish = false

[dependencies]
tokio.workspace = true
tokio-tungstenite.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
clap.workspace = true
anyhow.workspace = true
base64.workspace = true
